---
# CentOS 5 and OL 5 have a old version of Python that limit running
# Ansible gathering facts and some modules, that way we keep a 
# separated Playbook for 5 releases
- hosts: all
  gather_facts: no
  vars:
      convert2rhel_branch_name: master
      convert2rhel:
          requirements:
              - yum-utils
          pkg: convert2rhel
          repo_name: "convert2rhel"
          repo_desc: "convert2rhel copr repo"
          repo_file: /etc/yum.repos.d/convert2rhel.repo
      custom_repo:
          name: rhel
          description: Red Hat Enterprise Linux 5.11
          baseurl: "{{ rhel_repo }}"
          repo_file: /etc/yum.repos.d/RHEL511.repo

  tasks:
      - name: Install python-hashlib to make sha256 works with COPR repository
        raw: yum install -y python-hashlib

      - name: Add convert2rhel COPR repo
        raw: "echo \"[{{ convert2rhel.repo_name }}]\nname={{ convert2rhel.repo_desc }}\nbaseurl={{ copr_baseurl }}\ngpgcheck=0\nsslverify=0\" > {{ convert2rhel.repo_file }}"

      - name: Update system
        raw: "yum update -y"

      - name: Install requirement packages
        raw: "yum install -y {{ item }}"
        with_items: "{{ convert2rhel.requirements }}"

      - name: Find latest convert2rhel package available for specified branch
        raw: "repoquery --quiet --show-duplicates --qf '%{NAME}-%{VERSION}-%{RELEASE}' {{ convert2rhel.pkg }} | grep {{ convert2rhel_branch_name }} | sort | tail -n1"
        register: pkg_nvr

      - name: Install convert2rhel package
        raw: "yum install -y {{ item }}"
        with_items: "{{ pkg_nvr.stdout_lines }}"

      - name: Add Red Hat Enterprise Linux 5.11 .repo file
        raw: "echo \"[{{ custom_repo.name }}]\nname={{ custom_repo.description }}\nbaseurl={{ custom_repo.baseurl }}\ngpgcheck=0\" > {{ custom_repo.repo_file }}"
