[tool.black]
line-length=120
target-version=["py38"]

[tool.isort]
atomic=true
line_length = 120
lines_after_imports=2
lines_between_types=1
use_parentheses = true
balanced_wrapping = true
include_trailing_comma = true
multi_line_output = 3
known_third_party=[
    "pytest",
]
known_first_party=["convert2rhel"]

[tool.coverage.run]
branch = false
source = ["convert2rhel"]
omit = ["convert2rhel/unit_tests/*",]

[tool.coverage.paths]
source = ["convert2rhel/"]

[tool.coverage.report]
fail_under = 80
skip_covered = true
show_missing = true
