---
- name: Add convert2rhel COPR repo
  yum_repository:
    name: "{{ convert2rhel.copr.name }}"
    description: "{{ convert2rhel.copr.description }}"
    baseurl: "{{ convert2rhel.copr.baseurl }}"
    gpgcheck: no
    sslverify: no

- name: Update all the installed packages
  yum:
    name: '*'
    state: latest

- name: Install requirement packages
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
    state: latest
  with_items: "{{ convert2rhel.requirements }}"

- name: Find latest convert2rhel package available for specified branch
  raw: "repoquery --quiet --show-duplicates --qf '%{NAME}-%{VERSION}-%{RELEASE}' {{ convert2rhel.pkg }} | grep {{ convert2rhel_branch_name }} | sort | tail -n1"
  register: pkg_nvr

- name: Install latest convert2rhel package available for specified branch
  yum:
    name: "{{ item }}"
    disable_gpg_check: yes
    state: latest
  with_items: "{{ pkg_nvr.stdout_lines }}"
