- hosts: all
  become: yes
  strategy: free

  vars:
    rhsm_username: redhat-user-name
    rhsm_password: redhat-users-password
    skip_os_version_check: false
    # added for RHELDST-7822
    SSLCACERT: "https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem"

  tasks:

    - name: Validate Distribution (CentOS or Oracle Linux) and version
      fail:
        msg: "Distribution must be CentOS or Oracle Linux"
      when: ansible_distribution != 'CentOS' and ansible_distribution != 'OracleLinux'

    - name: Validate Release Version (6.10, 7.9, 8.4)
      fail:
        msg: "Distribution version must be 6.10, 7.9, or 8.4"
      when: (ansible_distribution_version != '6.10' and ansible_distribution_version != '7.9'
             and ansible_distribution_version != '8.4') or skip_os_version_check|bool

    - name: Download Red Hat GPG key
      get_url:
        url:  https://www.redhat.com/security/data/fd431d51.txt
        dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"

    # added for RHELDST-7822
    - name: Create rhsm/ca directory
      file:
        path: "/etc/rhsm/ca"
        state: directory
        owner: "root"
        group: "root"
        mode: '755'
        setype: "rhsmcertd_config_t"

    # added for RHELDST-7822
    - name: Download Red Hat SSL CA Cert
      get_url:
        url: "{{ SSLCACERT }}"
        dest: "/etc/rhsm/ca/redhat-uep.pem"

    - name: Add Convert2RHEL yum repository from Red Hat
      yum_repository:
        name: convert2rhel
        description: Convert2RHEL for OS {{ ansible_distribution_major_version }}
        baseurl: "https://cdn.redhat.com/content/public/convert2rhel/{{ ansible_distribution_major_version }}/x86_64/os/"
        enabled: yes
        gpgcheck: yes
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        sslcacert: "/etc/rhsm/ca/redhat-uep.pem"

    - name: Install Convert2RHEL
      yum:
        name: convert2rhel

    # NOTE 1: use the -y option to answer yes to all yes/no questions the
    # tool asks carefully and only after you have tested interactively to
    # ensure that there are not surprises within your environment.  Also
    # take care to read and follow all prerequisites and backup guidance documented at
    # https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index

    # NOTE 2: the following command may take 20-40 minutes on average to
    # complete, depending on quantity of packages installed and speed of
    # network and storage.  This will need to be run in parallel from the
    # control node or Tower to effectively run against many systems.

    - name: Run Convert2RHEL
      command: >
        convert2rhel
        -u "{{ rhsm_username }}"
        -p "{{ rhsm_password }}"
        --auto-attach
        --debug
        -y

    - name: reboot
      reboot:

    - name: recollect ansible facts on running distribution on system
      setup:
        gather_subset: 'distribution'

    - name: Verify system is converted to Red Hat Enterprise Linux (RHEL)
      assert:
        that: ansible_distribution == 'RedHat'
        msg: "OS conversion failed. OS is NOT Red Hat"
