name: test_coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_coverage_centos8:
    name: centos8 test_coverage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./Dockerfiles/centos8.Dockerfile
          tags: centos8
      - name: Run coverage
        run: |
          docker run centos8 pytest --cov=convert2rhel
