name: test_coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:        
  test_coverage:
    runs-on: ubuntu-latest
    container: centos:centos7

    steps:
    - uses: actions/checkout@v1

    - name: Install Requirements
      run: |
        yum install -y python-coverage python-nose python-six pexpect
        
    - name: Check test coverage
      run: |
        nosetests --with-coverage convert2rhel/
