name: Generate Manpages

on:
  pull_request:
    branches:
      - main

jobs:
  generate-manpages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.13

      - name: Generate Manpages
        run: |
          chmod +x scripts/manpage_generation.py
          bash scripts/manpage_generation.py
