name: Generate Manpages

on:
  pull_request:
    branches:
      - main

jobs:
  generate-manpages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run version check script
        run: |
          chmod +x scripts/manpage_generation.sh
          bash scripts/manpage_generation.sh
