name: Update Manpages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-manpages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip rpm rpm-python rpm-python3 rpm-devel
        pip install --upgrade pip
        pip install pexpect argparse-manpage

    - name: Verify Python Path
      run: |
        python -c "import sys; print(sys.path)"
        python -c "import pexpect; print('pexpect module is available.')"
        python -c "import rpm; print('rpm module is available.')"

    - name: Generate manpages
      run: |
        set -e

        # Directory to store the generated manpages
        MANPAGE_DIR='man'

        # Ensure the manpage directory exists
        mkdir -p "$MANPAGE_DIR"

        echo 'Generating manpages'

        # Generate a file with convert2rhel synopsis for argparse-manpage
        python -c 'from convert2rhel import toolopts; print("[synopsis]\n."+toolopts.CLI.usage())' > "$MANPAGE_DIR/synopsis"

        # Extract the current version from the spec file
        CURRENT_VER=$(grep -oP '^Version:\s+\K\S+' packaging/convert2rhel.spec)
        echo 'Current version: $CURRENT_VER'

        # Generate the manpage using argparse-manpage
        PYTHONPATH=. argparse-manpage --pyfile man/__init__.py --function get_parser --manual-title='General Commands Manual' --description='Automates the conversion of Red Hat Enterprise Linux derivative distributions to Red Hat Enterprise Linux.' --project-name 'convert2rhel $CURRENT_VER' --prog='convert2rhel' --include man/distribution --include man/synopsis > "$MANPAGE_DIR/convert2rhel.8"

        # Check for differences in the generated manpage
        if ! git diff --quiet HEAD -- "$MANPAGE_DIR/convert2rhel.8"; then
            echo 'Manpages are outdated. Please update them.'
            exit 1
        else
            echo 'Manpages are up-to-date.'
            exit 0
        fi
