name: Generate Manpages and Push to Fork

on:
  pull_request:
    branches:
      - main

jobs:
  generate-manpages-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and checkout branch
        run: git checkout -b auto_gen_man_fix

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          pip install argparse-manpage six pexpect

      - name: Install python3-rpm and python3-dnf packages with apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-rpm python3-dnf

      - name: Generate Manpages
        run: |
          chmod +x scripts/manpage_generation.sh
          bash scripts/manpage_generation.sh

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Fork
        run: |
          git push https://github.com/${{ github.actor }}/${{ github.repository_name }}.git HEAD:auto_gen_man_fix
