name: Update Manpages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-manpages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman

    - name: Build Podman image
      run: |
        podman build -t convert2rhel-manpages -f Containerfiles/manpage_check.Containerfile .

    - name: Run Podman container
      run: |
        podman run --rm convert2rhel-manpages
