name: pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting_centos6:
    name: centos6 linting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./Dockerfiles/centos6.Dockerfile
          tags: centos6
      - name: Run linting
        run: |
          docker run centos6 bash -c "scripts/run_lint.sh"
  linting_centos7:
    name: centos7 linting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./Dockerfiles/centos7.Dockerfile
          tags: centos7
      - name: Run linting
        run: |
          docker run centos7 bash -c "scripts/run_lint.sh"
  linting_centos8:
    name: centos8 linting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./Dockerfiles/centos8.Dockerfile
          tags: centos8
      - name: Run linting
        run: |
          docker run centos8 bash -c "scripts/run_lint.sh"
